{
    "message": {},
    "error_message": {
        "api": {
            "dot_env_variable_undefined": ".env 파일에 해당 변수가 정의되지 않았습니다.",
            "not_defined_env_variable": ".env 파일에 %{0} 변수가 정의되지 않았습니다.",
            "error_database_initialization": "데이터 소스 '%{0}' 초기화 중 오류가 발생했습니다.'"
        },
        "translate": {
            "wrong_number_of_parameters": "키 %{0}에 대한 매개 변수 수가 잘못되었습니다. 예상된 수는 %{1}이지만, %{2}이(가) 있습니다."
        },
        "http": {
            "success": "요청 작업이 성공적으로 처리되었습니다.",
            "created": "생성 작업이 성공적으로 처리되었습니다.'",
            "no_content": "내용 없음.",
            "bad_request": "잘못된 요청.",
            "unauthorized": "인증되지 않음.",
            "forbidden": "금지됨.",
            "not_found": "찾을 수 없음.",
            "already_exists": "이미 존재합니다.",
            "internal_server_error": "내부 서버 오류.",
            "critical_server_error": "심각한 오류가 발생했습니다.",
            "Unauthorized": "error_message.http.Unauthorized",
            "Forbidden": "error_message.http.Forbidden"
        },
        "password": {
            "failed_encrypt": "암호를 암호화하는 데 실패했습니다.",
            "failed_verify": "암호 검증에 실패했습니다."
        },
        "application": {
            "there_is_not_application_with_id": "id가 %{0}인 애플리케이션이 없습니다.",
            "application_with_id_not_found": "id가 %{0}인 애플리케이션을 찾을 수 없습니다.",
            "could_not_associate_application_and_user": "애플리케이션 %{0}과(와) 사용자 %{1}을(를) 연결할 수 없습니다."
        },
        "user": {
            "already_exist_user_same_password": "같은 사용자 이름을 가진 사용자가 이미 존재합니다.'",
            "could_not_created_user_with_username": "사용자 이름이 %{0}인 사용자를 만들 수 없습니다.",
            "user_with_id_not_found": "id가 %{0}인 사용자를 찾을 수 없습니다.",
            "user_with_username_not_found": "사용자 이름이 %{0}인 사용자를 찾을 수 없습니다.",
            "could_not_update_user": "사용자 이름이 %{0}인 사용자를 업데이트할 수 없습니다."
        }
    }
}
